#pragma config(Motor,  port1,           mPalka,        tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           mL,            tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           sRotate,       tmotorServoStandard, openLoop, driveRight)
#pragma config(Motor,  port6,           sHold,         tmotorServoStandard, openLoop)
#pragma config(Motor,  port7,           mLift,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           mRB,           tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           mConveer,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          mRF,           tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int count = 0;
int mat[2][3] = {{1, 2, 3},{1, 2, 3}};
/*
void mov1(char moto, int speedMotor, int time){
	motor[moto] = speedMotor;
	wait1Msec(time);
}

void mov2(char motor1, int speedMotor1, char motor2, int speedMotor2, int time){
	motor[motor1] = speedMotor1;
	motor[motor2] = speedMotor2;
	wait1Msec(time);
}

void mov3(char motor1, int speedMotor1, char motor2, int speedMotor2, char motor3, int speedMotor3, int time){
	motor[motor1] = speedMotor1;
	motor[motor2] = speedMotor2;
	motor[motor3] = speedMotor3;
	wait1Msec(time);
}
*/
void memoOne()
{
	motor[sHold] = 95;
	wait1Msec(1000);
	motor[mLift] = 40;
	motor[sRotate] = 127;
	wait1Msec(2000);
	motor[mLift] = -15;
	wait1Msec(1000);
	motor[sHold] = -10;
	wait1Msec(1000);
//	mov3(mRB, -20, mRF, -20, mL, -20, 100);
	motor[mLift] = 25;
	motor[sRotate] = 127;
	wait1Msec(2000);
	motor[sRotate] = -127;
//	wait1Msec(500);
	}



task main()
{
	motor[sRotate] = -127;

//fall
	motor[mPalka] = 50;
	wait1Msec(3000);
	motor[mPalka] = 90;
	motor[mLift] = -50;
	wait1Msec(200);
	motor[mPalka] = 90;
	wait1Msec(1000);
	motor[mPalka] = -90;
	wait1Msec(2000);

	motor[sRotate] = -127;
	motor[mRB] = 45;
	motor[mRF] = -55;
	motor[mLift] = 40;
	wait1Msec(1300);
	motor[mRB] = 0;
	motor[mRF] = 0;
	motor[mL] = 0;
	wait1Msec(500);

	motor[mLift] = 30;
	motor[mRB] = 20;
	motor[mRF] = 20;
	motor[mL] = 22;
	wait1Msec(1150);
	motor[mL] = 0;
	motor[mRB] = 0;
	motor[mRF] = 0;
	wait1Msec(1000);

	motor[mRB] = 30;
	motor[mRF] = -35;
	motor[mLift] = 30;
	wait1Msec(2200);
	motor[mRB] = 0;
	motor[mRF] = 0;
	wait1Msec(500);

	motor[mConveer] = 40;
	wait1Msec(1400);
	motor[mConveer] = 0;
	wait1Msec(500);

	motor[mLift] = -40;
	wait1Msec(500);

	for(int x = 0; x < 1; x++)
	{
		for(int y = 0; y < 1; y++)
		{
			motor[sRotate] = -127;
			memoOne();
			motor[mLift] = 40;
			motor[sRotate] = -127;
			motor[mConveer] = 60;
			wait1Msec(2400);
			motor[mLift] = -40;
			motor[mConveer] = 0;
			wait1Msec(500);
			memoOne();
		}
	}

	}
