#pragma config(Motor,  port1,           mPalka,        tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           mL,            tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           mRotate,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           sHold,         tmotorServoStandard, openLoop)
#pragma config(Motor,  port7,           mLift,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           mRB,           tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           mConveer,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          mRF,           tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int count = 0;

void mov1(char moto, int speedMotor, int time){
	motor[moto] = speedMotor;
	wait1Msec(time);
}

void mov2(char motor1, int speedMotor1, char motor2, int speedMotor2, int time){
	motor[motor1] = speedMotor1;
	motor[motor2] = speedMotor2;
	wait1Msec(time);
}

void mov3(char motor1, int speedMotor1, char motor2, int speedMotor2, char motor3, int speedMotor3, int time){
	motor[motor1] = speedMotor1;
	motor[motor2] = speedMotor2;
	motor[motor3] = speedMotor3;
	wait1Msec(time);
}

void memoOne(int x, int y, char rotate,
task main(){
/*
//fall
	mov1(mPalka, 50, 3000);
	mov2(mPalka, 90, mLift, -50, 200);
	mov1(mPalka, 90, 1000);
	mov1(mPalka, -90, 1000);
*/

	mov2(mRB, 50, mRF, -60, 500);
	motor[mLift] = 30;
	mov3(mRB, 50, mRF, 50, mL, 50, 500);


}
