#pragma config(Motor,  port1,           mPalka,        tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           mL,            tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           mRotate,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           mHold,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           mLift,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           mRB,           tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           mConveer,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          mRF,           tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	motor[mPalka] = 15;
	wait1Msec(3000);
	motor[mPalka] = 50;
	wait1Msec(500);
	motor[mPalka] = 50;
	wait1Msec(500);

	motor[mRB] = 100;
	motor[mRF] = -100;
	wait1Msec(1000);

	motor[mRB] = 70;
	motor[mRF]= 70;
	motor[mL] = 70
	wait1Msec(1000);

}
