#pragma config(Motor,  port1,           motRB,         tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port4,           motHre,        tmotorNone, openLoop)
#pragma config(Motor,  port5,           motRotate,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           motHolder,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           motLift,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           motL,          tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           motY,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          motRF,         tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	motor[motHre] = 0;
	wait1Msec(2000);
	motor[motHre] = 50;
	wait1Msec(1000);

	motor[motRB] = 100;
	motor[motRF] = -100;
	wait1Msec(1000);

	motor[motRB] = 70;
	motor[motRF]= 70;
	motor[motL] = 70
	wait1Msec(1000);

}
